import localFont from "next/font/local";
// import 'bootstrap/';
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapScript from '../components/BootstrapScript';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <BootstrapScript /> {/* Ensure Bootstrap JS is only included on the client */}
      </body>
    </html>
  );
}
